-- Migration 001: Document expanded model choices
-- Date: 2026-03-28
--
-- No structural changes needed. The active_model column is VARCHAR(50)
-- with no CHECK constraint. Validation happens in the provider registry
-- at runtime.
--
-- Valid model values:
--   gemini-2.5-flash (default)
--   gemini-2.5-pro
--   gpt-4o
--   gpt-4o-mini
--   claude-sonnet-4-20250514
--   claude-haiku-4-5-20251001
--
-- The default remains 'gemini-2.5-flash'.
